### ISSUE TITLE
How are a flight's emissions imputed to individual pax?

### ISSUE THREAD

**Issue by rplzzz** [milankl/CarbonFootprintAGU#24]
Each flight going to San Francisco that is carrying one or more AGU attendees would still have gone to San Francisco, even if the attendee(s) had decided to attend virtually.  However, the weight of the attendees and their luggage causes the flight to burn more fuel and create more emissions than it would have if the attendees had not been on board.  

My question is, do the figures in your analysis reflect this marginal contribution to the emissions by the attendees?  Or, are you using the attendees' pro rata share of the flight's total emissions?  If the latter, then you can't actually eliminate those emissions by having people attend the meeting virtually because the flights will still fly, and the emissions will still be emitted.  They will simply be imputed to other (non-attending) passengers.  Only the marginal emissions can be eliminated by having the attendees stay home.

**Comment by milankl** [comment]
The marginal contribution of a single person (say 75kg plus 15kg luggage = 90kg) is negligible to the weight of a typical aircraft+fuel+passengers+luggage+cargo O(80,000kg). 

For a given flight connection, it is true that the airplane would take off with or without that one additional scientist. However, following that logic no airline would ever change their flight schedules, which is clearly not true. Airlines adapt to customers, offering more connections wherever profitable or closing connections (e.g. some are only available in summer). The effect of people not taking a flight on the actual number of airplanes taking off is therefore delayed: It might take an airline some time to adapt to a change in demand, but they will because they want to maximise their profit and that especially means maximising the passenger load.

It is therefore entirely reasonable to distribute the carbon emissions of the airplane as pro rata share among the passengers. You can find more details in the references

[22] [Atmosfair, 2016. *atmosfair Flight Emissions Calculator: Documentation of the Method and Data*.](https://www.atmosfair.de/wp-content/uploads/atmosfair-flight-emissions-calculator-englisch-1.pdf)

[23] [International Civil Aviation Organization ICAO, 2017. *ICAO Carbon Emissions Calculator Methodology, Version 10*](https://www.icao.int/environmental-protection/CarbonOffset/Documents/Methodology%20ICAO%20Carbon%20Calculator_v10-2017.pdf)

[24] [Foundation myclimate, 2019. *The myclimate Flight Emission Calculator*.](https://www.myclimate.org/fileadmin/user_upload/myclimate_-_home/01_Information/01_About_myclimate/09_Calculation_principles/Documents/myclimate-flight-calculator-documentation_EN.pdf)

**Comment by rplzzz** [comment]
> ... following that logic no airline would ever change their flight schedules.

I disagree.  As you point out, airlines will change their schedule when the reduction in the number of passengers declines to the point that it's worth consolidating to a smaller number of flights.  There is, in other words, a collective action problem; nothing happens until enough people decide to act that they cross the threshold where the airline adjusts its schedule.  A proposed intervention that fails to meet this threshold will have no effect on emissions.  In particular, AGU attendance is almost certainly a negligible portion of any airline's passenger load, so changing the attendance habits of AGU participants (or, by extension, targeting any niche population) is by itself not likely to result in the reductions calculated.  

The best you can hope for is that the change in conference attendance will be part of a broad-based change in travel habits, which will cross the threshold for actual emissions reductions.  However, in that case it would be better to just calculate the emissions reduction due to the aggregate change in travel volume, rather than trying to impute those reductions to subpopulations.  The subpopulation results are likely to be misleading and possibly counterproductive, especially when the subpopulations are very small, like the one we're talking about here.

**Comment by milankl** [comment]
That's very fatalistic, Robert.
What's the difference that a single Swedish girl can make, simply by not attending School? But you give yourself already the answer. We don't just hope for a change in habits, no, we actively have to work on this, and a fatalistic world-view isn't helpful here. 

Also, you might have misunderstood the imputation. It's not about individual blaming, it's about the current conference model that is not sustainable for a low carbon society, not inclusive and not necessarily the most efficient and productive either. That's why I mentioned Linux: The kernel's [github repo](https://github.com/torvalds/linux) has about 24,000 contributors from all over the world, and they manage to release a new version every two months or so. Why? Because they were facing a problem when going open-source that it's difficult to communicate & merge all the efforts into a single working product. But Linus has found a solution, git. Yes, Linux developers still fly to conferences, but it's not mandatory to contribute. Why can we, i.e. AGU/EGU, not do it?

**Comment by rduerr** [comment]
Speaking as a long-time attendee of AGU from Colorado, I can positively say that the number of flights to San Francisco that have a very heavy concentration of AGU attendees is quite large!  It isn't unusual for practically everyone on the flight to be an AGU attendee.  That implies that at least a few flights might get canceled if fewer people flew to the AGU meeting!

**Comment by rplzzz** [comment]
> Speaking as a long-time attendee of AGU from Colorado, I can positively say that the number of flights to San Francisco that have a very heavy concentration of AGU attendees is quite large! It isn't unusual for practically everyone on the flight to be an AGU attendee. That implies that at least a few flights might get canceled if fewer people flew to the AGU meeting!

That's a testable hypothesis.  If it is true, then there should be a detectible increase in the number of flights to and from the AGU venue around the time of the conference.  The thing is, one has to actually do the research before drawing a conclusion.  We (rightly) castigate people who draw conclusions about climate change based on casual observations of their local weather, and we should hold ourselves to the same high standard.

BTW, I missed the previous response, and it looks like it's been a while, so I'll just pick one point:

> we actively have to work on this, and a fatalistic world-view isn't helpful here.

I don't think it's "fatalistic" to observe that collective action problems are famously hard to solve, that they usually require the formation of some sort of institutions, and that incentives matter a great deal.  Nobel prizes in economics have been awarded on all of those topics.  My thinking on the matter (which is mine alone, not speaking for anyone else) is that putting a sensible price on carbon emissions will do more to reduce emissions than any number of carbon footprint calculators.  Your mileage, of course, may vary.

**Comment by milankl** [comment]
Quick response on this
> detectible increase in the number of flights to and from the AGU venue around the time of the conference

This would only be true if airlines didn't have very adaptive pricing schemes, which makes the flights that are not preferred by AGU scientists cheaper. And don't forget that airlines' schedules have to comply constraints set by airport authorities - they can't change their schedules every week based on demand. That's why pricing schemes try to optimise passenger load.

**Comment by rplzzz** [comment]
I agree with all that, but remember the original hypothesis:
> at least a few flights might get canceled if fewer people flew to the AGU meeting!

If the airlines can absorb the AGU traffic without adding flights, then it stands to reason that they can absorb the loss of the AGU traffic without canceling flights.

**Comment by Goutte** [comment]
> A proposed intervention that fails to meet this threshold will have _no effect on emissions_.

Wrong.

#### Disqualifying the positive
> Disqualifying the positive refers to rejecting positive experiences by insisting they "don't count" for some reason or other. Negative belief is maintained despite contradiction by everyday experiences.

(https://en.wikipedia.org/wiki/False_dilemma)

---

_When people travel less, or less people travel, less energy is spent for travels._
If airlines decide to fly with empty planes (and waste their money), that's another issue..

---

Sorry if I come off as aggressive here ; my intent is to argue that even if changing the scientists' travel culture alone is not enough to effect a salient, measurable change (because of thresholds, as you correctly pointed out), it's still an effective change and should not be discarded as having _no effect_.

**Comment by milankl** [comment]
I think in the light of the current crisis it has been quite clear how quickly airlines can and will adapt to reduced demand.
